### ISSUE TITLE
Time based super like geneijin not consistent with their meter usage

### ISSUE THREAD

**Issue by Shodokan** [Grouflon/3rd_training_lua#15]
As long as refill option is used and set to full it will not properly show the meter usage over time from supers like Geneijin, seiei-enbu and oro sa1/3.  It will also not 

Half the time you do super and the time starts to go by it will not show and will continue to show full meter.

The other half it will function as it should.

It alternates.

If it is set to refill to an amount under full it will always not show timer.  UNLESS your "refill timer" is high enough to "naturally" get to full gauge from something else. 

example: https://streamable.com/kxb9lv

**Comment by Grouflon** [comment]
This is due to my weak comprehension of how the meter display work. Most of the systems of the game gets their display updated every frame, and thus automatically show changes as soon as you alter the variable in memory, but that's not the case for meter.
I believe the display only gets updated on some game events such as whiff, hit or block and I haven't found a way of forcing the update of the display yet.
If anyone has insight on this, it is truly welcome.

**Comment by Grouflon** [comment]
Well, I put some more effort and finally found a way to update the meter displays. There also was a subtlety that I didn't get at first for the time based SA.
Everything should work correctly on the next version (it's already on the dev branch, but the script on the dev branch will only work on fightcade's latest beta build at the moment)

**Comment by Grouflon** [comment]
The last version is out, it should be fixed with the last version of fightcade. Can you test on your side and confirm me that it's gone ?
