### ISSUE TITLE
Another Big Issue: Constant Negative Edge While Recording

### ISSUE THREAD

**Issue by Shodokan** [Grouflon/3rd_training_lua#18]
https://streamable.com/j0g4nn

Video explains everything.

When you are holding buttons, if you input a special or super... it will come out.  Like a constant negative edge.  Even though the button is never released.

**Comment by Grouflon** [comment]
This seems to occur on player 2 after you've swapped characters with the recording mode once.
There is actually a bug in the current implementation of lua in FBA that prevents swapping inputs correctly. That's why the current implementation of input swaps is a dirty hack that cause a lot of side effects. From what I have tested, this seems to be one of them.
Fortunately, the bug will probably be fixed in the next version of Fightcade's FBNeo fork, so we may be able to do it properly and fix the bug.
I'll keep you updated

**Comment by Grouflon** [comment]
The last version is out, it should be fixed with the last version of fightcade. Can you test on your side and confirm me that it's gone ?
